### PR TITLE
Change inline template to point to separate file

### PR DESCRIPTION
**Pull request by TWRaz**

### CODE REVIEW

**Comment by adobley** [comment]
Are you sure this works? I don't see a change to any of the configurations
to move the html file to the dist folder

**Comment by adobley** [comment]
I'd run the tests myself, I'm just out at the moment.

**Comment by TWRaz** [comment]
Works on my machine.

**Comment by adobley** [comment]
Alright. I tried the same thing earlier and had trouble getting it to pass
the tests. So I was surprised. I'll check it out tonight. Thanks!

**Comment by TWRaz** [comment]
You're telling me you don't have a CI pipeline setup yet? I'm going to have
to call off the demos I had lined up with those VCs.

**Comment by adobley** [comment]
Damn. I was hoping to sell to google before the end of this month. Maybe I
shouldn't have bought that mansion already.

**Comment by TWRaz** [comment]
At least you can resell the mansion. What am I supposed to with this life
size ice sculpture I commissioned of Abraham Lincoln riding a grizzly bear?
It's already starting to melt.

Also, don't merge. That commit fucks everything.

/Raz

**Pull request closed without merging**
